defaults:
  - _self_
  - user_settings: user_settings
  - hydra: base
  - model: caila_qwen3_8b
  - collection: merge_quality/merge_quality_easy
  - scorer: merge_quality
  - storage_adapter: local_jsonl
  - performance_monitor: disabled

group_id: "merge_quality_easy_qwen3_8b"

result_dir: ${user_settings.result_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}
dataset_root: ${user_settings.dataset_root}
slam_shared_config: ${oc.env:SLAM_SHARED_CONFIG_PATH, null}

hydra:
  searchpath:
    - file://${slam_shared_config}
